version: 1.0.{build}

branches:
  only:
    - master

image: 
  - Visual Studio 2017
  - Ubuntu

configuration:
  - Debug
  - Release

matrix:
  allow_failures:
    - os: Ubuntu
  fast_finish: true

build_script: 
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake c:/projects/allocators -G "Visual Studio 15"
  - cmd: cmake --build . --config "%CONFIGURATION%"
  - cmd: ctest -C "%CONFIGURATION%"

  - sh: mkdir build
  - sh: cd build
  - sh: cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} ..
  - sh: make
  - sh: ctest